### ISSUE TITLE
[Feature request]: 

### ISSUE THREAD

**Issue by vvrkz** [vikdevelop/timer#100]
### Describe the current problem or need

I'd like to have an infinite amounts of timers, and be able to arrange them and name them. Example; Egg [ 7 minutes], + bacon in oven [10 minutes + 30 seconds] and have them saved. So that I can use my computer as a cocking aid, as an example. Can't find any app on the store that has that function (I'm new to Linux). If you have the time, I'm grateful, yours truly <3

### Describe the solution you would like

Read the description 

### Do you have another solution?

I have many, but I think I'm going to have to charge money soon :) I just want to be able to use Linux.. and there isn't a decent clock on the system that I've found yet. It's like every developer lived in the basement of their moms ;) kisses! I do, no shame in that.

**Comment by vikdevelop** [comment]
Hello,
I will try to implement this feature in the future version.
