### ISSUE TITLE
[Bug]: No such file or directory: '/app/translations/et.json

### ISSUE THREAD

**Issue by meybonomme** [vikdevelop/timer#107]
### Linux distribution

Fedora 39

### Desktop environment

Gnome 45.2

### Version of Timer

latest

### Bug description

App won't open. My system language is Estonian (Language code is 'et').

Output of `flatpak run com.github.vikdevelop.timer`:

```
Traceback (most recent call last):
  File "/app/timer.py", line 19, in <module>
    locale = open(f"/app/translations/{r_lang}.json")
FileNotFoundError: [Errno 2] No such file or directory: '/app/translations/et.json'
```

**Comment by vikdevelop** [comment]
Hello, this shows because Estonian is not added to the translation languages. I will fix the problem in the next release.

**Comment by meybonomme** [comment]
Fall back language must be always English if translation is not present.
