### ISSUE TITLE
[Bug]: shortcuts don't work

### ISSUE THREAD

**Issue by FoggY9** [vikdevelop/timer#111]
### Linux distribution

Ubuntu 22.04

### Desktop environment

Gnome

### Version of Timer

latest

### Bug description

shortcuts doesn't work, im using flathub

**Comment by vikdevelop** [comment]
Hello,
please more specify your problem.
From the description "shortcuts doesn't work, im using flathub" I don't know what's the problem with shortcuts. It would also be ideal if you attached output from the command `flatpak run com.github.vikdevelop.timer` using terminal (Ctrl+Alt+T).
