### ISSUE TITLE
[Feature request]: adjust time with mouse wheel

### ISSUE THREAD

**Issue by Slater91** [vikdevelop/timer#112]
### Describe the current problem or need

Hello! Thanks for this application. Currently one needs to manually select the text field and input the numbers from the keyboard.

### Describe the solution you would like

I wonder how feasible it would be to allow the adjusting of time by scrolling on the field with the mouse wheel (or with the equivalent touchpad gesture), which would be much quicker.

Thanks!

**Comment by vikdevelop** [comment]
Hello, 
thank you for your feature request.
Currently, for selecting the time is used entry.
I will try to use another widget, that will allows you mentioned.
