### ISSUE TITLE
[Bug]: Closing one of multiple instance closes all instances

### ISSUE THREAD

**Issue by rubberplayer** [vikdevelop/timer#117]
### Linux distribution

debian 12.5

### Desktop environment

mate

### Version of Timer

latest

### Bug description

If I open two timers, and then close one, both timers are closed. Correct behavior imho would be : only the window the user wants to close is closed.

### Steps to reproduce

1. open an instance
2. open another instance
3. close one
4. both are closed

**Comment by vikdevelop** [comment]
Hello, please tell me the reasons why the user should need to open more than one window of the app. I can't think of any use cases where the user would need to open more than one window...

**Comment by vikdevelop** [comment]
Ok, I will add support for opening more than one window in the next release of the app (with support for the keyboard shortcut Ctrl+W). As far as the code goes, for me, I just need to tweak a few little things.

**Comment by rubberplayer** [comment]
Thanks ! Keep up the good work.

**Comment by vikdevelop** [comment]
I released a new version of the Timer app, that includes a shortcut for opening a new app window (finally Ctrl+N) and also has an improved header bar. It will be available to download in a few hours (although Flathub has had server problems in the last few weeks, so it is possible that it will be available for download in a few days).
