### ISSUE TITLE
[Bug]: Popup window no longer works in version 3.5

### ISSUE THREAD

**Issue by Silverreaper07** [vikdevelop/timer#134]
### Linux distribution

Ubuntu 22.04 LTS

### Desktop environment

GNOME 42.9

### Version of Timer

3.5 (latest)

### Bug description

I was earlier on Timer version 3.4.3 which had popup notifications working perfectly.What I mean by popup is when I set the countdown to say 20 min,after that I could minimize the application and do my work and when the timer was up ,the application window would pop up flawlessly.

Few days ago,I don't know how but the application updated by itself to version 3.5 and the popup no longer works.Even notifications do not come in the notification tray on the middle top.I have both "Show application icon in notification" and "Show application name in notification" checked in the options.

Kindly help me fix this or atleast provide me with instructions on how to build version 3.4.3 from source.There are no instructions present in README.md

**Comment by vikdevelop** [comment]
Hello,
I have Fedora with GNOME 47, and I can confirm, the popup window doesn't show after the finished timer; it only plays the sound. But, I apologize, it is not a problem with the application itself, but with the GNOME, specifically, with the GNOME 47 runtime, which uses the application, as it is available in Flatpak format. Downgrading to the older runtime versions is not recommended, as the 45 and lower versions are end of life, and additionally, they don't have newer widgets that are necessary for running the app.

As for notifications, it shows without any issues for me. After the finished timer, the app shows the notification at the top bar.

**Comment by Silverreaper07** [comment]
Is there any other way I can get the popup window to work?
