### ISSUE TITLE
libGL error on Time on Fedora 35 (flatpak version)

### ISSUE THREAD

**Issue by taw00** [vikdevelop/timer#3]
```
[todd@localhost ~]$ flatpak run com.github.vikdevelop.timer 
libEGL warning: MESA-LOADER: failed to retrieve device information

libEGL warning: DRI2: could not open /dev/dri/card0 (No such file or directory)
libGL error: MESA-LOADER: failed to retrieve device information
Timer is running ...
No provider of glGetShaderiv found.  Requires one of:
    Desktop OpenGL 2.0
    OpenGL ES 2.0
```

**Comment by vikdevelop** [comment]
Try allow in Flatseal "GPU acceleration" (device=dri). Or enter command in terminal
```
flatpak run com.github.vikdevelop.timer --device=dri
```

**Comment by taw00** [comment]
`flatpak run --device=dri com.github.vikdevelop.timer`

Apparently, the order matters. That worked.

I then install installed `flatseal` (which I had never heard of) and flipped that switch.

Thanks for the response. -t

**Comment by vikdevelop** [comment]
I'll add this permission to Flathub manifest to make work Timer out of the box on really all distributions that support Flatpak.
