### ISSUE TITLE
Timer does not even open?

### ISSUE THREAD

**Issue by Melonadev** [vikdevelop/timer#41]
Operating system: Pop!_OS 22.04 LTS x86_64
Desktop environment: GNOME 42.3.1
Timer version: 2.7

**Steps to reproduce behaviour**:
1. Press the Super/Windows key (to bring up the Search function for apps) OR Open the 'Show Applications' app
2. Type in 'Timer' (this Timer app should be selected)
3. Press the Enter key to open the Timer app.

**Desired behaviour**:
Timer opens.

**Actual behaviour**:
~~Depends, but Timer usually opens after a system restart. Subsequently, timer does not open.~~
Timer does not open.

**Comment by vikdevelop** [comment]
Try open Terminal (Ctrl + Alt + T) and type `flatpak run com.github.vikdevelop.timer` and paste output of this command here. 
I tried on Pop!_OS 22.04 (GNOME 42.5, Virtualization in GNOME Boxes) open from Pop!_OS menu and terminal and no problems.

**Comment by Melonadev** [comment]
That works. Maybe I have to update GNOME for this issue to be resolved.

**Comment by Melonadev** [comment]
Just shut down and turned on my laptop. Now neither method works. Timer does not open.

**Comment by vikdevelop** [comment]
Try in terminal `killall python3` and then command `flatpak run com.github.vikdevelop.timer` and paste output of this command here.

**Comment by vikdevelop** [comment]
I have uploaded a new version which will (hopefully) fix this problem on Flathub. You should see the Timer update in a few hours. Let me know if it works or not.

**Comment by Melonadev** [comment]
It works now!
