### ISSUE TITLE
Pausing the timer

### ISSUE THREAD

**Issue by Melonadev** [vikdevelop/timer#43]
Once I press 'Start' and the Timer starts counting down, there could be a 'Pause' button to freeze the time countdown.

Currently the 'Stop' button completely exits the countdown and resets the timer.

**Comment by vikdevelop** [comment]
Good idea. I will add this feature to the next release :)

**Comment by vikdevelop** [comment]
This option has been added to next update of Timer. In a few hours will be available on Flathub.

**Comment by vikdevelop** [comment]
New version with option of pausing timer is available on Flathub.
