### ISSUE TITLE
[Feature request]: Ability to change 'Action' options while timer is counting down

### ISSUE THREAD

**Issue by Melonadev** [vikdevelop/timer#73]
### Describe the current problem or need

Currently, there are 3 action settings available upon opening Timer: 'Action after finished timer', 'Play beep', and 'Custom notification text'.
![image](https://user-images.githubusercontent.com/66422959/225782958-a4808dac-18ff-4d93-bda2-41f2d6ce9c7a.png)

But when counting down, these settings are no longer visible or editable, so I can't change the settings unless I stop the timer:
![image](https://user-images.githubusercontent.com/66422959/225783199-4aaf9a49-a3bf-4619-879d-2c18938e054d.png)

### Describe the solution you would like

I would like the 3 action settings described above to still be visible and editable even when Timer is counting down.

**Comment by vikdevelop** [comment]
Hello, thank you for the tip. Is it possible to add an "Edit options" button on the countdown page. When you press it, the timer will pause and a dialog or a new page will appear where you can edit the items you mentioned. There would be an "Apply" button at the top, pressing it would start the timer with the new settings. Would that work?

**Comment by Melonadev** [comment]
That can do, but I'd prefer for the timer to continue counting down while I edit the settings.

**Comment by vikdevelop** [comment]
Okay, I'll try to implement it.

**Comment by vikdevelop** [comment]
New version with this feature has been published on Flathub. It availables to download will in a few hours.
