### ISSUE TITLE
[Feature request]: Clicking a field should select the entire text

### ISSUE THREAD

**Issue by aryzing** [vikdevelop/timer#83]
### Describe the current problem or need

Clicking on a time field inserts a cursor rather than selecting the entire field's text. Given some of the fields are 0 by default, it's not a great experience to have to first delete the zero and then add a number. Tabbing through the fields selects the entire text, would be nice if clicking did the same for easier and more conveneint editing.

### Describe the solution you would like

Clicking on a field should select its entire text.

**Comment by vikdevelop** [comment]
Currently, widget Adw.EntryRow() has no support for this feature. Anyway, I will try to implement it.
