### ISSUE TITLE
[Feature request]: Transparent timer

### ISSUE THREAD

**Issue by zhum** [vikdevelop/timer#89]
### Describe the current problem or need

The timer is very useful during any video presentations/conferences/etc. The present state is OK for breaks, but it would be cool to have ability put the timer over the presentation or any other screen sharing to check how many time passed or left.

In this mode the timer should be semi-transparent ( % should be tunable), and if possible - pass the cursor clicks under itself (except the header, which is used to stop timer or move the window). The second feature is optional.

### Describe the solution you would like

Implement level of the transparency for the window and "always-on-top" behavior.

### Do you have another solution?

Some window managers support can set always-on-top flag and custom window transparency, but it should be done every time and not all WMs support it.

**Comment by vikdevelop** [comment]
Hello, if you are using GNOME desktop, there is an extension called "Focus" that makes an inactive window transparent. The LibAdwait library does not allow transparent windows, there is only a dark and light theme in the base. Additional settings can be made in Gradience, but I'm not sure if it can set a transparent window.

**Comment by vikdevelop** [comment]
Hello, if you are using GNOME desktop, there is an extension called "Focus" that makes an inactive window transparent. The LibAdwaita library does not allow transparent windows, there is only a dark and light theme in the base. Additional settings can be made in Gradience, but I'm not sure if it can set a transparent window.
